[package]
name = "gecko-mqtts"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.57"
bytes = "1.2.1"
log = "0.4.17"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
