[package]
name = "gecko-mqtts"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
bytes = "1.2.1"
log = "0.4"
serde = { version = "1.0.142", features = ["derive"] }
thiserror = "1"
tokio = { version = "1.20.1", features = ["full"] }
